import { IItem } from '../Interface'

export const terrainItems: IItem[] = [
    { texFile: 'terrainart\\lordaeronsummer\\lords_dirt', title: 'Ldrt', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronsummer\\lords_dirtrough', title: 'Ldro', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronsummer\\lords_dirtgrass', title: 'Ldrg', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronsummer\\lords_rock', title: 'Lrok', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronsummer\\lords_grass', title: 'Lgrs', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronsummer\\lords_grassdark', title: 'Lgrd', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronfall\\lordf_dirt', title: 'Fdrt', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronfall\\lordf_dirtrough', title: 'Fdro', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronfall\\lordf_dirtgrass', title: 'Fdrg', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronfall\\lordf_rock', title: 'Frok', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronfall\\lordf_grass', title: 'Fgrs', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronfall\\lordf_grassdark', title: 'Fgrd', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronwinter\\lordw_dirt', title: 'Wdrt', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronwinter\\lordw_dirtrough', title: 'Wdro', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronwinter\\lordw_snowgrass', title: 'Wsng', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronwinter\\lordw_rock', title: 'Wrok', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronwinter\\lordw_grass', title: 'Wgrs', scale: '2:1' },
    { texFile: 'terrainart\\lordaeronwinter\\lordw_snow', title: 'Wsnw', scale: '2:1' },
    { texFile: 'terrainart\\barrens\\barrens_dirt', title: 'Bdrt', scale: '2:1' },
    { texFile: 'terrainart\\barrens\\barrens_dirtrough', title: 'Bdrh', scale: '1:1' },
    { texFile: 'terrainart\\barrens\\barrens_pebbles', title: 'Bdrr', scale: '1:1' },
    { texFile: 'terrainart\\barrens\\barrens_dirtgrass', title: 'Bdrg', scale: '1:1' },
    { texFile: 'terrainart\\barrens\\barrens_desert', title: 'Bdsr', scale: '2:1' },
    { texFile: 'terrainart\\barrens\\barrens_desertdark', title: 'Bdsd', scale: '2:1' },
    { texFile: 'terrainart\\barrens\\barrens_rock', title: 'Bflr', scale: '1:1' },
    { texFile: 'terrainart\\barrens\\barrens_grass', title: 'Bgrr', scale: '2:1' },
    { texFile: '', title: 'Adrt', scale: '1:1' },
    { texFile: '', title: 'Adrd', scale: '1:1' },
    { texFile: '', title: 'Agrs', scale: '1:1' },
    { texFile: '', title: 'Arck', scale: '1:1' },
    { texFile: '', title: 'Agrd', scale: '1:1' },
    { texFile: '', title: 'Avin', scale: '1:1' },
    { texFile: '', title: 'Adrg', scale: '1:1' },
    { texFile: '', title: 'Alvd', scale: '1:1' },
    { texFile: 'terrainart\\felwood\\felwood_dirt', title: 'Cdrt', scale: '2:1' },
    { texFile: 'terrainart\\felwood\\felwood_dirtrough', title: 'Cdrd', scale: '2:1' },
    { texFile: 'terrainart\\felwood\\felwood_poison', title: 'Cpos', scale: '2:1' },
    { texFile: 'terrainart\\felwood\\felwood_rock', title: 'Crck', scale: '2:1' },
    { texFile: 'terrainart\\felwood\\felwood_vines', title: 'Cvin', scale: '1:1' },
    { texFile: 'terrainart\\felwood\\felwood_grass', title: 'Cgrs', scale: '2:1' },
    { texFile: 'terrainart\\felwood\\felwood_leaves', title: 'Clvg', scale: '1:1' },
    { texFile: 'terrainart\\northrend\\north_dirt', title: 'Ndrt', scale: '2:1' },
    { texFile: 'terrainart\\northrend\\north_dirtdark', title: 'Ndrd', scale: '1:1' },
    { texFile: 'terrainart\\northrend\\north_rock', title: 'Nrck', scale: '2:1' },
    { texFile: 'terrainart\\northrend\\north_grass', title: 'Ngrs', scale: '2:1' },
    { texFile: 'terrainart\\northrend\\north_ice', title: 'Nice', scale: '2:1' },
    { texFile: 'terrainart\\northrend\\north_snow', title: 'Nsnw', scale: '2:1' },
    { texFile: 'terrainart\\northrend\\north_snowrock', title: 'Nsnr', scale: '1:1' },
    { texFile: '', title: 'Ydrt', scale: '1:1' },
    { texFile: '', title: 'Ydtr', scale: '1:1' },
    { texFile: '', title: 'Yblm', scale: '1:1' },
    { texFile: '', title: 'Ybtl', scale: '1:1' },
    { texFile: '', title: 'Ysqd', scale: '1:1' },
    { texFile: '', title: 'Yrtl', scale: '1:1' },
    { texFile: '', title: 'Ygsb', scale: '1:1' },
    { texFile: '', title: 'Yhdg', scale: '1:1' },
    { texFile: '', title: 'Ywmb', scale: '1:1' },
    { texFile: '', title: 'Vdrt', scale: '1:1' },
    { texFile: '', title: 'Vdrr', scale: '1:1' },
    { texFile: '', title: 'Vcrp', scale: '1:1' },
    { texFile: '', title: 'Vcbp', scale: '1:1' },
    { texFile: '', title: 'Vstp', scale: '1:1' },
    { texFile: '', title: 'Vgrs', scale: '1:1' },
    { texFile: '', title: 'Vrck', scale: '1:1' },
    { texFile: '', title: 'Vgrt', scale: '1:1' },
    { texFile: '', title: 'Qdrt', scale: '1:1' },
    { texFile: '', title: 'Qdrr', scale: '1:1' },
    { texFile: '', title: 'Qcrp', scale: '1:1' },
    { texFile: '', title: 'Qcbp', scale: '1:1' },
    { texFile: '', title: 'Qstp', scale: '1:1' },
    { texFile: '', title: 'Qgrs', scale: '1:1' },
    { texFile: '', title: 'Qrck', scale: '1:1' },
    { texFile: '', title: 'Qgrt', scale: '1:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_dirt', title: 'Xdrt', scale: '2:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_dirtrough', title: 'Xdtr', scale: '2:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_blackmarble', title: 'Xblm', scale: '1:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_bricktiles', title: 'Xbtl', scale: '1:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_squaretiles', title: 'Xsqd', scale: '1:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_roundtiles', title: 'Xrtl', scale: '1:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_grass', title: 'Xgsb', scale: '2:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_grasstrim', title: 'Xhdg', scale: '1:1' },
    { texFile: 'terrainart\\dalaran\\dalaran_whitemarble', title: 'Xwmb', scale: '1:1' },
    { texFile: '', title: 'Ddrt', scale: '1:1' },
    { texFile: '', title: 'Dbrk', scale: '1:1' },
    { texFile: '', title: 'Drds', scale: '1:1' },
    { texFile: '', title: 'Dlvc', scale: '1:1' },
    { texFile: '', title: 'Dlav', scale: '1:1' },
    { texFile: '', title: 'Ddkr', scale: '1:1' },
    { texFile: '', title: 'Dgrs', scale: '1:1' },
    { texFile: '', title: 'Dsqd', scale: '1:1' },
    { texFile: 'terrainart\\dungeon2\\gdirt', title: 'Gdrt', scale: '2:1' },
    { texFile: 'terrainart\\dungeon2\\gbrick', title: 'Gbrk', scale: '2:1' },
    { texFile: 'terrainart\\dungeon2\\gredstones', title: 'Grds', scale: '1:1' },
    { texFile: 'terrainart\\dungeon2\\glavacracks', title: 'Glvc', scale: '2:1' },
    { texFile: 'terrainart\\dungeon2\\glava', title: 'Glav', scale: '1:1' },
    { texFile: 'terrainart\\dungeon2\\gdarkrocks', title: 'Gdkr', scale: '1:1' },
    { texFile: 'terrainart\\dungeon2\\ggreystones', title: 'Ggrs', scale: '2:1' },
    { texFile: 'terrainart\\dungeon2\\gsquaretiles', title: 'Gsqd', scale: '1:1' },
    { texFile: '', title: 'Zdrt', scale: '1:1' },
    { texFile: '', title: 'Zdtr', scale: '1:1' },
    { texFile: '', title: 'Zdrg', scale: '1:1' },
    { texFile: '', title: 'Zbks', scale: '1:1' },
    { texFile: '', title: 'Zsan', scale: '1:1' },
    { texFile: '', title: 'Zbkl', scale: '1:1' },
    { texFile: '', title: 'Ztil', scale: '1:1' },
    { texFile: '', title: 'Zgrs', scale: '1:1' },
    { texFile: '', title: 'Zvin', scale: '1:1' },
    { texFile: '', title: 'Idrt', scale: '1:1' },
    { texFile: '', title: 'Idtr', scale: '1:1' },
    { texFile: '', title: 'Idki', scale: '1:1' },
    { texFile: '', title: 'Ibkb', scale: '1:1' },
    { texFile: '', title: 'Irbk', scale: '1:1' },
    { texFile: '', title: 'Itbk', scale: '1:1' },
    { texFile: '', title: 'Iice', scale: '1:1' },
    { texFile: '', title: 'Ibsq', scale: '1:1' },
    { texFile: '', title: 'Isnw', scale: '1:1' },
    { texFile: '', title: 'Odrt', scale: '1:1' },
    { texFile: '', title: 'Odtr', scale: '1:1' },
    { texFile: '', title: 'Osmb', scale: '1:1' },
    { texFile: '', title: 'Ofst', scale: '1:1' },
    { texFile: '', title: 'Olgb', scale: '1:1' },
    { texFile: '', title: 'Orok', scale: '1:1' },
    { texFile: '', title: 'Ofsl', scale: '1:1' },
    { texFile: '', title: 'Oaby', scale: '1:1' },
    { texFile: '', title: 'Kdrt', scale: '1:1' },
    { texFile: '', title: 'Kfsl', scale: '1:1' },
    { texFile: '', title: 'Kdts', scale: '1:1' },
    { texFile: '', title: 'Kfst', scale: '1:1' },
    { texFile: '', title: 'Ksmb', scale: '1:1' },
    { texFile: '', title: 'Klgb', scale: '1:1' },
    { texFile: '', title: 'Ksqt', scale: '1:1' },
    { texFile: '', title: 'Kdkt', scale: '1:1' },
    { texFile: '', title: 'Jdrt', scale: '1:1' },
    { texFile: '', title: 'Jdtr', scale: '1:1' },
    { texFile: '', title: 'Jblm', scale: '1:1' },
    { texFile: '', title: 'Jbtl', scale: '1:1' },
    { texFile: '', title: 'Jsqd', scale: '1:1' },
    { texFile: '', title: 'Jrtl', scale: '1:1' },
    { texFile: '', title: 'Jgsb', scale: '1:1' },
    { texFile: '', title: 'Jhdg', scale: '1:1' },
    { texFile: '', title: 'Jwmb', scale: '1:1' },
    { texFile: '', title: 'cAc2', scale: '1:1' },
    { texFile: '', title: 'cAc1', scale: '1:1' },
    { texFile: '', title: 'cBc2', scale: '1:1' },
    { texFile: '', title: 'cBc1', scale: '1:1' },
    { texFile: '', title: 'cKc1', scale: '1:1' },
    { texFile: '', title: 'cKc2', scale: '1:1' },
    { texFile: '', title: 'cYc2', scale: '1:1' },
    { texFile: '', title: 'cYc1', scale: '1:1' },
    { texFile: '', title: 'cXc2', scale: '1:1' },
    { texFile: '', title: 'cXc1', scale: '1:1' },
    { texFile: '', title: 'cJc2', scale: '1:1' },
    { texFile: '', title: 'cJc1', scale: '1:1' },
    { texFile: '', title: 'cDc2', scale: '1:1' },
    { texFile: '', title: 'cDc1', scale: '1:1' },
    { texFile: '', title: 'cCc2', scale: '1:1' },
    { texFile: '', title: 'cCc1', scale: '1:1' },
    { texFile: '', title: 'cIc2', scale: '1:1' },
    { texFile: '', title: 'cIc1', scale: '1:1' },
    { texFile: '', title: 'cFc2', scale: '1:1' },
    { texFile: '', title: 'cFc1', scale: '1:1' },
    { texFile: '', title: 'cLc2', scale: '1:1' },
    { texFile: '', title: 'cLc1', scale: '1:1' },
    { texFile: '', title: 'cWc2', scale: '1:1' },
    { texFile: '', title: 'cWc1', scale: '1:1' },
    { texFile: '', title: 'cNc2', scale: '1:1' },
    { texFile: '', title: 'cNc1', scale: '1:1' },
    { texFile: '', title: 'cOc1', scale: '1:1' },
    { texFile: '', title: 'cOc2', scale: '1:1' },
    { texFile: '', title: 'cZc2', scale: '1:1' },
    { texFile: '', title: 'cZc1', scale: '1:1' },
    { texFile: '', title: 'cGc2', scale: '1:1' },
    { texFile: '', title: 'cGc1', scale: '1:1' },
    { texFile: '', title: 'cVc2', scale: '1:1' },
    { texFile: '', title: 'cVc1', scale: '1:1' },
    { texFile: '', title: 'cQc2', scale: '1:1' },
    { texFile: '', title: 'cQc1', scale: '1:1' },

    // TODO; Merge texFile and scale with above based on title

    // { texFile: 'terrainart\\blight\\outland_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\lordw_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\ashen_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\barrens_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\druins_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\village_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\villagefall_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\north_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\dungeon_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\lordf_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\ice_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\felwood_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\cave_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\lords_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\citadel_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blight\\ruins_blight', title: '', scale: '2:1' },

    // { texFile: 'terrainart\\ruins\\ruins_roundtiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ruins\\ruins_dirtrough', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ruins\\ruins_dirt', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\ruins\\ruins_largebricks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\ruins\\ruins_dirtgrass', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ruins\\ruins_sand', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ruins\\ruins_smallbricks', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ruins\\ruins_grassdark', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ruins\\ruins_grass', title: '', scale: '2:1' },

    // { texFile: 'terrainart\\dungeon\\cave_dirt', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\dungeon\\cave_lavacracks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\dungeon\\cave_redstones', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dungeon\\cave_lava', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dungeon\\cave_brick', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\dungeon\\cave_darkrocks', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dungeon\\cave_squaretiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dungeon\\cave_greystones', title: '', scale: '2:1' },

    // { texFile: 'terrainart\\icecrown\\ice_blacksquares', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\icecrown\\ice_snow', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\icecrown\\ice_ice', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\icecrown\\ice_cracks', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\icecrown\\ice_runebricks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\icecrown\\ice_blackbricks', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\icecrown\\ice_dirtrough', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\icecrown\\ice_dirt', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\icecrown\\ice_tiledbricks', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\icecrown\\ice_darkice', title: '', scale: '1:1' },

    // { texFile: 'terrainart\\nothing\\nothing', title: '', scale: '1:1' },

    // { texFile: 'terrainart\\blackcitadel\\citadel_roughdirt', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_flatstones', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_smallbricks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_largebricks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_dirtlight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_darktiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_squaretiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\blackcitadel\\citadel_dirt', title: '', scale: '1:1' },

    // { texFile: 'terrainart\\outland\\outland_abyss', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\outland\\outland_dirtlight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\outland\\outland_dirtcracked', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\outland\\outland_flatstones', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\outland\\outland_dirt', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\outland\\outland_roughdirt', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\outland\\outland_flatstoneslight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\outland\\outland_rock', title: '', scale: '1:1' },

    // { texFile: 'terrainart\\villagefall\\villagefall_dirtrough', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_cobblepath', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_grassshort', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_rocks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_crops', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_blight', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_dirt', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_stonepath', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\villagefall\\villagefall_grassthick', title: '', scale: '2:1' },

    // { texFile: 'terrainart\\cityscape\\city_blackmarble', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\cityscape\\city_dirtrough', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\cityscape\\city_dirt', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\cityscape\\city_bricktiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\cityscape\\city_squaretiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\cityscape\\city_grasstrim', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\cityscape\\city_grass', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\cityscape\\city_whitemarble', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\cityscape\\city_roundtiles', title: '', scale: '1:1' },

    // { texFile: 'terrainart\\dalaranruins\\druins_roundtiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_dirtrough', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_grasstrim', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_bricktiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_squaretiles', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_blackmarble', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_whitemarble', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_grass', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\dalaranruins\\druins_dirt', title: '', scale: '2:1' },

    // { texFile: 'terrainart\\village\\village_grassthick', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\village\\village_cobblepath', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\village\\village_stonepath', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\village\\village_rocks', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\village\\village_crops', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\village\\village_dirt', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\village\\village_dirtrough', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\village\\village_grassshort', title: '', scale: '1:1' },

    // { texFile: 'terrainart\\ashenvale\\ashen_grasslumpy', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_dirtrough', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_vines', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_leaves', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_dirtgrass', title: '', scale: '1:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_grass', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_rock', title: '', scale: '2:1' },
    // { texFile: 'terrainart\\ashenvale\\ashen_dirt', title: '', scale: '2:1' },
]
